### ISSUE TITLE
Failed to ask anonymous user

### ISSUE THREAD

**Issue by gmkung** [nathanrchn/perplexityai#11]
Thanks for building this @nathanrchn ! 

Is this class still usable as-is? 
When running it, I get errors on the 'ask_anonymous_user' step.

Here is the error message after catching the error:
```
    assert self.ask_anonymous_user(), "Failed to ask anonymous user"
AssertionError: Failed to ask anonymous user
```

**Comment by nathanrchn** [comment]
I just committed new changes to fix this issue. Please tell me if it works now.

**Comment by gmkung** [comment]
It works now! Thank you @nathanrchn :)
The API is a bit slow to return results and sometimes times out but that's on the side of Perplexity I guess. 
Thanks!

**Comment by nathanrchn** [comment]
The api is slow because the `search` method returns the `Answer` only once and I haven't yet coded a stream version. I will try to do it.

**Comment by LexiestLeszek** [comment]
having this error when deploying on vercel/render but dont have it when running through ngrok. Any ideas how to fix it?

**Comment by itsklimov** [comment]
I got it after a few days of the initial try, expiration is for tomorrow. Can you add another check?
