### ISSUE TITLE
Set timeout

### ISSUE THREAD

**Issue by theurs** [nathanrchn/perplexityai#13]
Sometimes the search freezes for a very long time, you need to set a timeout somehow.

**Comment by nathanrchn** [comment]
Thanks for spotting this. I've added a timeout in the search method.

**Comment by theurs** [comment]
new version always throw

**Comment by nathanrchn** [comment]
I added a new method called `search_sync` for searching without streaming the answer. The final dict is similar to the `Answer` class but with more values.
