### ISSUE TITLE
Resolving Status=Pending results

### ISSUE THREAD

**Issue by gmkung** [nathanrchn/perplexityai#14]
Hi, I'm testing out the latest version of the code, where everything is condensed into the Perplexity.py file.
The generator that's returned from perplexity.search some times returns status=Pending with answer =''. What should we do in those scenarios to get a proper final answer?

**Comment by nathanrchn** [comment]
I have added something in the `on_message` to avoid that the generator returns the last status=pending message and a status=completed message because the status=completed is the same as the last status=pending message. Surely that's what makes this mistake. Make sure that you have the latest version of the repo. Can you tell me in witch cases it appends ?

**Comment by gmkung** [comment]
Thanks. I tested again, and this time I dumped the results and realised that when I get pending, it's because I took only the first entry in the generator. Some times (when I do queries quickly after each other),I get an enormous number of status=pending responses before getting a status=completed response at the end of the generator. I can write logic to filter only the completed results, but it would be great if the pending results can be filtered out altogether.

**Comment by nathanrchn** [comment]
To get only the completed messages use the `search_sync` method that returns the answer without streaming it.

**Comment by gmkung** [comment]
I tried search_sync and it seems to give me completed results most times, but some times it still gives me status=Pending. Here is one example.

{"status": "pending", "uuid": "c80093ad-1fa3-40a3-865d-1697860a671c", "read_write_token": null, "final": false, "backend_uuid": "a3fd97e8-803d-421d-b8d6-51dfd1db3e2f", "mode": "concise", "search_focus": "internet", "gpt4": false, "display_model": "turbo", "answer": "", "web_results": [{"name": "Venus: vETH Token | Address 0xf508fcd89b8bd15579dc79a6827cb4686a3592c8 | BscScan", "url": "https://bscscan.com/address/0xf508fcd89b8bd15579dc79a6827cb4686a3592c8", "meta_data": null, "is_attachment": false}, {"name": "Venus ETH (vETH) ERC20 Token Analytics | Binance (BNB) Smart Chain Mainnet | Bitquery", "url": "https://explorer.bitquery.io/bsc/token/0xf508fcd89b8bd15579dc79a6827cb4686a3592c8", "meta_data": null, "is_attachment": false}, {"name": "0xf508fcd89b8bd15579dc79a68...", "url": "https://blockscan.com/address/0xf508fcd89b8bd15579dc79a6827cb4686a3592c8", "meta_data": null, "is_attachment": false}], "chunks": [""], "extra_web_results": [], "image_metadata": []}

**Comment by nathanrchn** [comment]
You may not have the latest version of the code, as I have modified this error. The error is on line 184: you need `return self.queue.pop(-1)` and not `return self.queue.pop(0)`. Try to pull the newest version.

**Comment by gmkung** [comment]
Oh yeah indeed the only difference i have vs the latest version is that line. Thanks!
