### ISSUE TITLE
Answer format after the last committ

### ISSUE THREAD

**Issue by SilviaBerardelli** [nathanrchn/perplexityai#15]
After the last commit (2nd October), the answer format displayed is the next one (JSON file).
The only chance to manage it is to manually access to the answer or there is any way to get the "readable" answer?

Code:
```
perplexity = Perplexity()
answer = perplexity.search("What is the meaning of life?")
for a in answer:
    print(a)
perplexity.close()
```
Answer:
`{'status': 'completed', 'uuid': '022b9019-9640-4d6d-839d-55ccc85a9214', 'read_write_token': 'fd8a9036-c177-414e-ab93-cb9a1c2341b9', 'query_str': 'What is the meaning of life?', 'related_queries': ['Meaning of life examples', 'What is the meaning of life quotes', 'What is the meaning of life in psychology'], 'personalized': False, 'attachments': [], 'search_focus': 'internet', 'label': '', 'backend_uuid': '1107f7f5-ef76-4672-820a-7a258d4cc134', 'mode': 'concise', 'display_model': 'turbo', 'step_type': 'FINAL', 'gpt4': False, 'context_uuid': '80eee334-2c3d-4774-b31f-d3abfed4bdc4', 'thread_title': '', 'thread_access': 2, 'thread_url_slug': 'What-is-the-EQf39e92RnKCCnoljUzBNA', 'author_username': None, 'author_image': None, 's3_social_preview_url': 'https://ppl-ai-public.s3.amazonaws.com/static/img/pplx-default-preview.png', 'answer': 'The meaning of life pertains to the significance of living or existence in general[1]. It is a question that has been asked in many ways, such as "Why are we here?", "What is life all about?", or "What is the purpose of existence?"[1]. The meaning of life can be derived from philosophical and religious contemplation of, and scientific inquiries about, existence, social ties, consciousness, and happiness[1]. Many other issues are also involved, such as symbolic meaning, ontology, value, purpose, ethics, good and evil, free will, the existence of one or multiple gods, conceptions of God, the soul, and the afterlife[1]. \n\nWhile philosophy is often unhelpful in providing concrete answers, people who believe that they know their life’s meaning enjoy greater well-being than those who don’t[2]. One 2019 study found that agreeing with the statement “I have a philosophy of life that helps me understand who I am” was associated with fewer symptoms of depression and higher positive affect[2]. \n\nThe meaning of life is not something that exists outside of ourselves, but rather something that we create[5]. Meaning is like the water of our psychological health. Without it, our hearts and minds will shrivel and die. And like water, meaning flows through us—what is important today is not what was important years ago, and what is important tomorrow will not be the same as what is important today[5]. In a very real sense, the meaning of life is therefore to create meaning[5].', 'web_results': [{'name': 'Meaning of life', 'url': 'https://en.wikipedia.org/wiki/Meaning_of_life', 'snippet': 'The meaning of life pertains to the significance of living or existence in general. Many other related questions include: "Why are we here?", "What is life all about?", or "What is the purpose of existence?"', 'meta_data': None, 'is_attachment': False, 'is_widget': False, 'is_map': False}, {'name': 'The Meaning of Life Is Surprisingly Simple - The Atlantic', 'url': 'https://www.theatlantic.com/family/archive/2021/10/meaning-life-macronutrients-purpose-search/620440/', 'snippet': 'Coherence: how events fit together. This is an understanding that things happen in your life for a reason. · Purpose: the existence of goals and ...', 'meta_data': None, 'is_attachment': False, 'is_widget': False, 'is_map': False}, {'name': 'The Meaning of Life - Stanford Encyclopedia of Philosophy', 'url': 'https://plato.stanford.edu/entries/life-meaning/', 'snippet': 'A standard distinction to draw is between the meaning “in” life, where a human person is what can exhibit meaning, and the meaning “of” life in ...', 'meta_data': None, 'is_attachment': False, 'is_widget': False, 'is_map': False}, {'name': 'What Is the Meaning of Life? - Psychology Today', 'url': 'https://www.psychologytoday.com/us/blog/hide-and-seek/201803/what-is-the-meaning-life', 'snippet': 'The meaning of life is that which we choose to give it.', 'meta_data': None, 'is_attachment': False, 'is_widget': False, 'is_map': False}, {'name': 'What Is the Meaning of Life? | Mark Manson', 'url': 'https://markmanson.net/the-meaning-of-life', 'snippet': "Meaning is not something that exists outside of ourselves. It is not some cosmic universal truth waiting to be discovered. It is not some grand 'eureka' moment ...", 'meta_data': None, 'is_attachment': False, 'is_widget': False, 'is_map': False}, {'name': '4 philosophical answers to the meaning of life - Big Think', 'url': 'https://bigthink.com/thinking/four-philosophical-answers-meaning-of-life/', 'snippet': 'Having a sense of purpose in life is associated with positive health outcomes; conversely, not having one can leave a person feeling listless ...', 'meta_data': None, 'is_attachment': False, 'is_widget': False, 'is_map': False}], 'chunks': ['', 'The meaning of', ' life pertains to', ' the significance', ' of living or', ' existence in', ' general[1]. It', ' is a question', ' that has been', ' asked in many', ' ways, such as', ' "Why are we here', '?", "What is life', ' all about?", or', ' "What is the', ' purpose of existence', '?"[1]. The meaning', ' of life can be', ' derived from', ' philosophical', ' and religious', ' contemplation of', ', and scientific', ' inquiries about', ', existence, social', ' ties, consciousness', ', and happiness', '[1]. Many other', ' issues are also', ' involved, such', ' as symbolic meaning', ', ontology, value', ', purpose, ethics', ', good and evil', ', free will, the', ' existence of', ' one or multiple', ' gods, conceptions of', ' God, the soul', ', and the after', 'life[1]. \n\nWhile philosophy', ' is often unhelpful in', ' providing concrete', ' answers, people', ' who believe that', ' they know their', ' life’s meaning', ' enjoy greater', ' well-being than', ' those who don', '’t[2]. One 2019 study', ' found that agreeing', ' with the statement', ' “I have a philosophy', ' of life that', ' helps me understand', ' who I am” was', ' associated with', ' fewer symptoms', ' of depression', ' and higher positive', ' affect[2]. \n\nThe meaning', ' of life is not', ' something that', ' exists outside', ' of ourselves', ', but rather something', ' that we create', '[5]. Meaning', ' is like the water', ' of our psychological', ' health. Without', ' it, our hearts', ' and minds will', ' shrivel and die', '. And like water', ', meaning flows', ' through us—what is', ' important today', ' is not what was', ' important years', ' ago, and what', ' is important', ' tomorrow will', ' not be the same', ' as what is important', ' today[5]. In', ' a very real sense', ', the meaning', ' of life is therefore', ' to create meaning', '[5].'], 'extra_web_results': [{'name': 'Three Ways to See Meaning in Your Life - Greater Good Science Center', 'url': 'https://greatergood.berkeley.edu/article/item/three_ways_to_see_meaning_in_your_life', 'snippet': "Researchers' definitions of meaning in life typically incorporate three themes: the belief that your life and contributions matter to others and ...", 'meta_data': None, 'is_attachment': False, 'is_widget': False, 'is_map': False}, {'name': 'Life Definition & Meaning - Merriam-Webster', 'url': 'https://www.merriam-webster.com/dictionary/life', 'snippet': '1. a. : the quality that distinguishes a vital and functional being from a dead body · 2. a · 3. : biography sense 1 · 4. : spiritual existence transcending (see ...', 'meta_data': None, 'is_attachment': False, 'is_widget': False, 'is_map': False}], 'image_metadata': []}`

**Comment by nathanrchn** [comment]
The only way to get the answer is to take the answer from this JSON dict. Personally, I don't think returning a dataclass object is useful in this situation, as it would simplify `a["answer"]` into `a.answer`. In addition, I'll add utils methods to return only the next token for simplicity.

**Comment by SilviaBerardelli** [comment]
Thanks @nathanrchn ! How about the personalization of the "profile"? Is there any way to "guide" the AI individualizing the user profile (as you can do in the official website). I'd like to tell the AI to answer just if the question is in a specific context and no more.

**Comment by nathanrchn** [comment]
You have to be logged in to access this feature. Use `Perplexity(my@email.com` instead of just `Perplexity()` when you create the session.
