### ISSUE TITLE
Avoid detection by antispam

### ISSUE THREAD

**Issue by ch-amal0** [nathanrchn/perplexityai#16]
Hello,

Something strange happens when I ask many prompts in a few seconds. My script does not crash but the AI doesn't answer as well, and my script keeps running forever. Setting timeout in `search` method allows to move to the next query but the problem is similar. The only way to move on is to kill script and start it again.
It always happen after 8 or 9 successful queries.

I assume that this is not a bug from this code, but probably a security from the website. Any idea about how to bypass this ? I don't have a billion queries to ask, only 15/20.

**Comment by nathanrchn** [comment]
Yes I made a mistake when I reversed engineer their internal api. This should works now with the last commit.
