### ISSUE TITLE
Module not found utils

### ISSUE THREAD

**Issue by laserman2000** [nathanrchn/perplexityai#17]
I get the following error after updating to the latest version (which is probably related to the new utils.py):

ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-2-f3369d7abe5a>](https://localhost:8080/#) in <cell line: 1>()
----> 1 from perplexity import Perplexity
      2 perplexity = Perplexity("[antonioskondis@gmail.com](mailto:antonioskondis@gmail.com)")

[/usr/local/lib/python3.10/dist-packages/perplexity/__init__.py](https://localhost:8080/#) in <module>
      1 name: str = "perplexity"
      2 
----> 3 import utils
      4 from .labs import Labs
      5 from .perplexity import Perplexity

ModuleNotFoundError: No module named 'utils'

**Comment by nathanrchn** [comment]
I just fixed this issue in the last commit.
