### ISSUE TITLE
TypeError: 'builtin_function_or_method' object is not subscriptable

### ISSUE THREAD

**Issue by Yassine-El-M** [nathanrchn/perplexityai#19]
Thanks for this great repository.
Unfortunately, I got this error : 

![image](https://github.com/nathanrchn/perplexityai/assets/78159196/837e9c30-1887-43bb-a468-52df90e75e22)

**Comment by nathanrchn** [comment]
Yes I made an error. I have fixed that.

**Comment by nathanrchn** [comment]
Try to uninstall it and then re-install it.

**Comment by Yassine-El-M** [comment]
Thanks for the response, just if anyone had the same issue, try uninstalling from command prompt.

Anyway, now I got a different issue : websocket error: Handshake status 400 BAD REQUEST

As shown in the screenshot it just keeps running and it doesn't stop until I interrupt it.

![image](https://github.com/nathanrchn/perplexityai/assets/78159196/327df579-0c20-4700-a2ec-b38b135c45d0)
