### ISSUE TITLE
Trying to run many queries quickly

### ISSUE THREAD

**Issue by krishmoran** [nathanrchn/perplexityai#20]
I saw in recent commits it showed that there was a fix for making more than 9 requests, but still when I run a bunch of queries in a for-loop i get rate-limited. How to fix this? Or, what's the best way to harvest like 100-1000 requests using this?

**Comment by nathanrchn** [comment]
The only way to get such high rates is to have several instances of Perplexity. The rate limit is a limit set by the Perplexity system and you can't change it.

**Comment by krishmoran** [comment]
And how to achieve the multiple instances? Multiple Perplexity() objects or
another way?

**Comment by nathanrchn** [comment]
Yes try to create multiple instances of the class.

**Comment by krishmoran** [comment]
What do you think about running requests concurrently or in parallel? I haven't been able to crack this, I have a function that opens the object and closes it after one call, and running with a few threads in a loop gets me about 100 responses until it freezes up and times out. So I'm wondering where the bottleneck is here because the number of successful calls varies each time I run it

**Comment by krishmoran** [comment]
I think async needs to be considered as well in order for the multi responses to be sent and received in order to prevent things from breaking. But looks like at base its synchronousity is causing issues with this even running without concurrency.
