### ISSUE TITLE
Stuck in search function

### ISSUE THREAD

**Issue by lixiaochuan2020** [nathanrchn/perplexityai#22]
My codes are like:
"""
1 from perplexity import Perplexity
2 perplexity = Perplexity()
3 answer = perplexity.search("What is the meaning of life?")
4 for a in answer:
5     print(a)
6 perplexity.close()
"""
When I run this, it just stuck in line 3, which is "search" function. After a long time, I will get this error message: websocket error: [Errno 60] Operation timed out.
Is there any solution?

**Comment by nathanrchn** [comment]
There is surely a problem with your network. Do you use a proxy?

**Comment by lixiaochuan2020** [comment]
Yes, if I do not use a proxy, I will get this error:
<img width="927" alt="CleanShot 2023-10-09 at 20 06 01@2x" src="https://github.com/nathanrchn/perplexityai/assets/83334710/eafd80de-97ac-4168-8efe-8f4bf9115db6">

**Comment by lixiaochuan2020** [comment]
After setting the proxy in code by 'os.environ["http"] & ["https"] ', it wors now!
