### ISSUE TITLE
New problems with cloudflare and user agent

### ISSUE THREAD

**Issue by ch-amal0** [nathanrchn/perplexityai#28]
It looks like Perplexity update their protection, as the same problem as https://github.com/nathanrchn/perplexityai/issues/10 is back.

It looks like I am not the only one noticing this (see https://github.com/nathanrchn/perplexityai/issues/27)

Error : 
```
return loads(self.session.get(
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
```

Return from self.session.get(...).text : 
```html
<!DOCTYPE html>
<html lang="en-US">
<head>
<title>Just a moment...</title>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta http-equiv="X-UA-Compatible" content="IE=Edge"><meta name="robots" content="noindex,nofollow"><meta name="viewport" content="width=device-width,initial-scale=1">
<link href="/cdn-cgi/styles/challenges.css" rel="stylesheet">
</head>
<body class="no-js">
<div class="main-wrapper" role="main">
<div class="main-content">
<noscript>
<div id="challenge-error-title">
<div class="h2">
<span class="icon-wrapper">
<div class="heading-icon warning-icon">
</div>
</span>
<span id="challenge-error-text">Enable JavaScript and cookies to continue
</span>
</div>
</div>
</noscript>
</div>
</div>

</body></html>
```

**Comment by SilviaBerardelli** [comment]
same issue! I think just @nathanrchn can help us, because he knows how to manage the user agent

**Comment by nathanrchn** [comment]
I just changed the User-Agent and it seems to work now.

**Comment by gmkung** [comment]
Yes verified that it works again now! Thanks!

**Comment by SilviaBerardelli** [comment]
Still not working for me :( same issue: JSONDecodeError: Expecting value: line 1 column 1 (char 0)
how to manage it? Anyone else tried and it works?

**Comment by phamxtien** [comment]
It works after update UA

**Comment by laserman2000** [comment]
> Still not working for me :( same issue: JSONDecodeError: Expecting value: line 1 column 1 (char 0) how to manage it? Anyone else tried and it works?

+1, not working for me on Google Colab (email login or generic)

**Comment by camphora** [comment]
still now working for me , it works fine 18 hours ago but now it seems wrong

**Comment by laserman2000** [comment]
Is there anybody that has this working as of today? I've tried with various servers with no response.

**Comment by gmkung** [comment]
O yeah it stopped working for me again today :(

**Comment by ch-amal0** [comment]
It's working fine for me since the update from @nathanrchn from last week. Make sure you are using the last commit
