### ISSUE TITLE
get_sid is error

### ISSUE THREAD

**Issue by phamxtien** [nathanrchn/perplexityai#3]
```
    def get_sid(self) -> str:
        url = f"https://www.perplexity.ai/socket.io/?EIO=4&transport=polling&t={self.t}"
        print(url)
        response = self.session.get(url=url)
        print(response.text)
        response = loads(response.text[1:])
        return response["sid"]
```
print(url) >> https://www.perplexity.ai/socket.io/?EIO=4&transport=polling&t=9e6f78e3
print(response.text) >> html source page, 
not return 0{"sid":"mCJ2kEzFS-_QMjHEAIBk","upgrades":["websocket"],"pingTimeout":20000,"pingInterval":25000} as expected.

**Comment by nathanrchn** [comment]
It works now
