### ISSUE TITLE
websocket error: Handshake status 400 Bad Request

### ISSUE THREAD

**Issue by Yassine-El-M** [nathanrchn/perplexityai#32]
Hello,

I'm using jupyter lab and I got this error when I run the code :
websocket error: Handshake status 400 Bad Request

![image](https://github.com/nathanrchn/perplexityai/assets/78159196/830824a9-abc3-439f-a36b-ec9d18d3aa98)

I also noticed that the cell keeps running forever.

I made sure to install the last version of the repository, and also websocket.

**Comment by krishmoran** [comment]
was this issue solved yet? @nathanrchn

**Comment by hishamag-student** [comment]
same issue, any help!!

**Comment by hishamag-student** [comment]
@Yassine-El-M after searching, I found the issue is coming from the version of websocket-client library, so i install the version 1.6.2 and its worked.
you can check with : pip list , to see the version of websocket-client and then install the updated one.

**Comment by Yassine-El-M** [comment]
@hishamag-student Wow ! It worked thanks a lot !

**Comment by Yassine-El-M** [comment]
@hishamag-student Wow ! It worked thanks a lot !
