### ISSUE TITLE
Failed to ask anonymous user again

### ISSUE THREAD

**Issue by itsklimov** [nathanrchn/perplexityai#46]
I got it after a few days of the initial try, expiration is for tomorrow. Can you add another check?

**Comment by phamxtien** [comment]
It runs smooth on my side.
Try access https://www.perplexity.ai/ via your browser, wait to pass captcha and try again

**Comment by itsklimov** [comment]
[https://github.com/nathanrchn/perplexityai/pull/47](url) not sure why this was happening but self._ask_anonymous_user() can through the errors even when session recovered, here is the pull request

**Comment by itsklimov** [comment]
still not working, after a night not using it, it starts throwing error. and the only way I found to recover it is to delete the session file.
Someone else has this issue?
