### ISSUE TITLE
Error: Handshake status 400 BAD REQUEST

### ISSUE THREAD

**Issue by guz6** [nathanrchn/perplexityai#6]
After setting up the env and dependencies, I got this error when I run the test code. Do you know how to fix it? I tried to modify user-agent and still had that issue. Thank you very much.

**Comment by nathanrchn** [comment]
I'm sorry, but I just ran the test code and it works. It may be a proxy or internet configuration problem. I'm on mac and everything works fine.

**Comment by guz6** [comment]
Is it possible to zoom with you if I can not figure out this error? Thank you very much.
