### ISSUE TITLE
Typing [*NUMBER*] crashes Labs

### ISSUE THREAD

**Issue by BaalNetbek** [nathanrchn/perplexityai#61]
Typing from numbers in range from 0 to 99 in square brackets, for example "[47]", in the prompt crashes the labs.perplexity.ai site displaying ```Application error: a client-side exception has occurred (see the browser console for more information).``` in the middle of black screen.

Console says:
![obraz](https://github.com/user-attachments/assets/a1d10af4-bbc4-41c2-b1da-52b8e8a39270)

**Comment by nathanrchn** [comment]
I have the same problem when I try in the browser. I don't know what is causing this error.
